# Generated by Django 3.2.25 on 2024-03-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='linke',
            new_name='link',
        ),
    ]
